version: "3.8"

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./shared_folder:/home/node/test
    environment:
      - N8N_SECURE_COOKIE=false
    extra_hosts:
      - "host.docker.internal:host-gateway"
    stdin_open: true   # same as -it
    tty: true          # same as -it
    restart: unless-stopped  # replaces --rm for persistence

volumes:
  n8n_data:
    name: "n8n_data"
    external: true
